blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/lambda-sh/lambda/discussions
    about: Use discussions for general questions, ideas, or community support.
