[package]
name = "lambda-audio-tool"
version = "2023.1.30"
edition = "2021"

[[bin]]
name = "lambda-audio"
path = "src/main.rs"

[dependencies]
lambda-rs = { path = "../../crates/lambda-rs", version = "2023.1.30", default-features = false, features = ["audio"] }
